### ISSUE TITLE
Fix iter8 Grafana dashboard

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/docs#120]
May need controller changes. When identified, create issue.

**Comment by sriumcp** [comment]
Based on our discussion, we are:

- [ ] We are deleting `istio.json` and `knative.json` files which seem redundant (after making sure they are indeed redundant).
- [ ] We are verifying `from` & `to` variables encoded in the Grafana URL generated by the controller work as expected.
- [ ] We are adding support for `kind=service` in addition to `kind=deployment` without increasing the number of templates from 4 to 8.

**Comment by sushmarchandran** [comment]
@huang195 @sriumcp: Please take a look and let me know what you think

List of variables required form the controller:

- kind: `service`, `deployment`
- baseline: <already provided; internal query has been modified>
- candidate: <already provided; internal query has been modified>
- window_size: <already provided; no changes>
- namespace: <already provided; internal query has been modified>
- pod_field: `pod`, `pod_name` <value changes depending on kubernetes version, hidden variable>
- job_field: `istio_mesh`, `envoy_stats` <value changes based on telemetry version, hidden variable>

Other variable values calculated internally (not provided by the controller):

- destination_field: `destination_service_name`, `destination_workload` <calculated based on $kind variable, hidden variable>
- namespace_field: `destination_service_namespace`, `destination_workload_namespace` <calculated based on $kind variable, hidden variable>

**Comment by huang195** [comment]
@sushmarchandran do we want to deal with istio telemetry version at this time? If we do, you need to add 2 more variables, 1 to deal with `_seconds_` or `_milliseconds` for the latency metric, and 1 to deal with the multiplier to convert units to milliseconds. If not, we can remove `job_field` for now and add it later with the other 2 in another PR. Either way works. Other than that, it looks good.

**Comment by sushmarchandran** [comment]
@huang195 Yes. you're right. I will work on the telemetry diffs once I am done with the services/deployments and Kubernetes version modifications on Grafana.

**Comment by sriumcp** [comment]
@sushmarchandran The above changes (without job_field) look good to me. 

Could you also please document the new Grafana URL format below, which the controller needs to output? If you provide a few examples and describe what each of them mean (very brief is ok), it would help with the controller PR.

**Comment by sushmarchandran** [comment]
Sample (modified) Graphing URL:
`http://localhost:3000/d/eXPEaNnZz/iter8-application-metrics?var-kind=deployment&var-namespace=bookinfo-iter8&var-service=reviews&var-baseline=reviews-v3&var-candidate=reviews-v5&var-pod_field=pod&from=1576820317351&to=1576820377696`

New variables:
1. var-kind: takes the values: `service` or `deployment` - indicates the kind of experiment being conducted, i.e with services or with deployments
2. var-pod_field: takes the values: `pod` or `pod_name` - indicates the version of experiment being used, i.e pod for vk8 >= 16 and pod_name for vk8 < 16

**Comment by sushmarchandran** [comment]
Resolved in https://github.com/iter8-tools/iter8/pull/288
