### ISSUE TITLE
Latency metric definition 

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/docs#127]
- Confirm that v1.0.0 can use histogram percentile latency metrics.
- Get numerator and denominator of the ratio metric

**Comment by sushmarchandran** [comment]
I can confirm that this works for v1.0.0.
I tested with telemetry v1 of Istio. We will have to use slightly different queries for telemetry v2. But goal can be achieved either way.

If we have an SLO/SLA that at least 95% of requests should have latency within 500ms: we can use something like this:
Numerator: `(sum(increase(istio_request_duration_seconds_bucket{le='0.5', destination_workload="details-v1",destination_workload_namespace="bookinfo-iter8"}[1h])) by (destination_workload, destination_workload_namespace, le))`
Denominator: `(sum(increase(istio_request_duration_seconds_bucket{destination_workload="details-v1",destination_workload_namespace="bookinfo-iter8"}[1h])) by (destination_workload, destination_workload_namespace, le))`

This query has been specifically written for the `details-v1` deployment in the `bookinfo-iter8` namespace. The only issue with this kind of query is that we only have a fixed number of buckets exposed by Istio to Prometheus. And the smallest bucket size is itself big enough to accommodate all the requests. 

Also, as discussed with @sriumcp offline, I confirmed that using the `rate` function will calculate the " per-second average rate of increase of the time series in the range vector": https://prometheus.io/docs/prometheus/latest/querying/functions/#rate

**Comment by sriumcp** [comment]
@sushmarchandran Looks good to me. However, before we close this, can I suggest two changes?

Could we please make this compatible with telemetry v2 (so, job = envoy stats and metrics = milliseconds buckets) instead of telemetry v1?

@fabolive I don't think you will bring up telemetry v1 / v2 in your talk or recordings. But I suggest that all the examples you use are targeted towards v2 (since v1 is deprecated).

**Comment by sushmarchandran** [comment]
@sriumcp I verified that this works. As you've mentioned, v2 telemetry will require us to change the job filter to `job = 'envoy-stats'` as well as the metric name to `istio_request_duration_milliseconds_bucket`.
