### ISSUE TITLE
Launch A/B/n Campaign

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#174]
1. **Title:** Going beyond canary releases in Kubernetes using A/B/n rollouts
- Write medium blog post
- Identify slack channels and circulate blog post

2. Simplify A/B/n tutorial
 - Reduce detail on create your own metrics (simply provide the command and point to metrics section for details)
 - Eliminate Prometheus configuration (investigate if enabling mTLS for bookinfo will work better with Istio's default prom config)

3. Showcase iter8 enhancements
 - Incorporate and highlight match clause in the tutorial in the context of user-stickiness
 - Custom metrics CRD

4. Implement related bug fixes / other enhancements
 - Make iter8-analytics resilient to transient prom glitches (retry prom with timeouts)
 - Re-enable e2e tests for iter8-analytics (and controller)

5. Stretch goals
 - Investigate and mitigate flip-flopping phenomenon in analytics service

**Comment by kalantar** [comment]
looks like this was replaced by https://github.com/iter8-tools/iter8/issues/303. Closing. If you disagree @sriumcp reopen
