### ISSUE TITLE
Document how to solve namespace hang issue

### ISSUE THREAD

**Issue by huang195** [iter8-tools/docs#180]
When iter8-controller is deleted before namespaces that contain experiments CRs are deleted, it will result in namespaces not being able to be deleted. This would require manual steps of removing finalizers from experiment CRs. We should at least add a "Troubleshooting" section to our documentation

**Comment by kalantar** [comment]
This is related to https://github.com/iter8-tools/iter8/issues/116 isn't it @kimikowang ?

I agree that at the very least we need to document the workaround.

**Comment by kalantar** [comment]
@huang195 did https://github.com/iter8-tools/docs/pull/250 address your concern?

**Comment by sriumcp** [comment]
Done.
