### ISSUE TITLE
Question about forking and clone the docs fork

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#189]
@Alan-Cha 

I noticed a couple of minor things when trying to update the docs.

1. When I fork and git clone, i.e., when I do `git clone --recurse-submodules https://github.com/sriumcp/docs.git`, I see a `docs` folder and not a `hugo-iter8-docs` folder. This is a bit different from what the documentation expected me to believe. We might either way to change the documentation, or the folder name created by the git clone command (not sure how).

2. When I serve using `hugo serve`, I see the message `Web Server is available at //localhost:1313/ (bind address 127.0.0.1)` on my terminal. Is there a way to add the missing `https:` prefix to the URL?

**Comment by Alan-Cha** [comment]
@sriumcp 

I'm planning on completely redoing the documentation after we start using Netlify. It is currently very out of date.

> folder name created by the git clone command

Actually this is very easy and very useful to do! You just add the desired name of the folder after the `git clone` command. I use it all the time when reviewing PRs on my other open-source libraries. 

> Is there a way to add the missing `https:` prefix to the URL?

I also noticed this. I haven't looked into it yet though.
