### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/docs#209]
This issue identifies changes that should be made to the documentation at the time of the next release. These changes are in addition to the standard change of PREVIOUS_RELEASE --> RELEASE in links.

- [ ] identify changes (add below)
- [x] update grafana link to install script to be https://raw.githubusercontent.com/iter8-tools/iter8/v1.0.0/integrations/grafana/install_dashboard.sh
- [x] update link to iter8 v0.2.1 in Kiali documentation
- [x] update link in experiment documentation to crd yaml file
- [x] review for capitalization of Kubernetes and Docker. See https://kubernetes.io/docs/contribute/style/style-guide/#kubernetes-io-word-list
- [x] validate links
- [x] ensure all videos inserted

**Comment by kalantar** [comment]
I've added everyone;  please document new changes in this release. Be brief; this will be put in the changelog. Here is a starting point:

- support for A/B/n rollout
- new Experiment CRD
- new analytics
- new tutorials
- updated look and feel of documentation

**Comment by sriumcp** [comment]
Pre kubecon.

**Comment by kalantar** [comment]
I object to the closing of this issue; v1.0.0 has NOT been released.

**Comment by sriumcp** [comment]
1. Address model change issue (router spec)
2. Address test coverage requirements
