### ISSUE TITLE
Design & test a single prom configmap for A/B/n tutorial across Istio versions

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#283]
Needs to work across Istio versions

**Comment by sriumcp** [comment]
Make  sure solution works across Istio versions.

**Comment by sriumcp** [comment]
Check the prometheus configuration that comes with demo profile. 

If it solves the prometheus scrape problem automatically (e.g., in 1.7 onwards), then see if the same configuration can be used for solving the problem in earlier Istio versions.

If not, try applying the following prom config across Istio versions: https://raw.githubusercontent.com/istio/istio/release-1.7/manifests/charts/istio-telemetry/prometheus/templates/configmap.yaml is the configuration 

The goal is to find a single prometheus configuration, that we can `kubectl apply` and make prometheus scraping for custom metrics work across Istio versions 1.4+ onwards.

This will also help re-enable e2e tests for a/b/n scenario.

**Comment by kalantar** [comment]
decided not to do
