### ISSUE TITLE
Landing page changes in preparation for Canary A/B/n CLI campaign

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#288]
Surface key value propositions
 - Clean up wordings for individual cards

**Comment by Alan-Cha** [comment]
We discussed some of the changes we would like to make during our Friday playback meeting.

This [document](https://ibm.ent.box.com/notes/725856288824?s=gaxikdvufhqfg63y5qzgd3swn9fqg7vx) summarizes some of the changes we would like to make but there is a lot more to discuss, including the specifics.

**Comment by sriumcp** [comment]
1. Highlights right upfront
2. Fix order of cards
3. Live experiments / or something else instead of continuous experimentation ; card
4. CI/CD card
5. Kiali-iter8 card: trends absorbed as part of it
6. Under-the-hood-look card: do a HIL experiment to understand insights surfaced by iter8
