### ISSUE TITLE
Rename branches to match the archival links

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/docs#373]
Current branch names have the pattern: `release-<version number>` while the the archival links have the pattern: `https://v<version number>.iter8.tools`. Does it make sense to ensure that they conform to the same pattern?

For example:

`release-1.0.0` vs `https://v1-0-0.iter8.tools`

**Comment by sriumcp** [comment]
@Alan-Cha Yes, I think ensuring consistency between release names and branch names does make sense to me.

**Comment by Alan-Cha** [comment]
@sriumcp @fabolive @kalantar I will make the changes but I was also thinking, should we also consider changing the name of the preview site `preliminary.iter8.tools` to `preview.iter8.tools`? 

I think it makes sense to try to align the branch names with the archival links. Perhaps it makes sense to do the same with the preview site?

My only concerns is that 1) we are breaking away from the pattern that Istio set forth that we would like to emulate (minor issue) 2) We may have already set a precedent by using the `preliminary.iter8.tools` subdomain. 

Thoughts?
