### ISSUE TITLE
Amplify KUI and MLOps blog articles

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/docs#376]

**Comment by sriumcp** [comment]
Channel: KFServing + iter8 integration slack
Do a before and after check for following metrics: git stars, page visits, git issues by users, slack threads by users.

**Comment by Alan-Cha** [comment]
Regarding sharing these articles (and future ones) on social media and news media websites like Reddit and Hacker News, do we want to create an iter8 account for all of these?

I do not know how feasible it is to share these accounts. There is also the issue of responding to comments. We may receive questions that only certain people can answer. In any case, the article writer is most likely the most capable of replying. 

I do not know how feasible all of this is, but do we want to come up with a strategy to help guide us in online presence, account sharing, and responding to comments?

**Comment by sriumcp** [comment]
Account creation makes sense -- at least so that we will be notified if there is a comment or a question (for us to respond back to).

**Comment by sriumcp** [comment]
Done.
