### ISSUE TITLE
Release v0.2 shiny new documentation

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#48]
**Acceptance Criteria:** Make it better than the current git based markdown

Replace canary analysis picture
Replace grafana picture for iter8-trend
Star us on Github should take users to the correct location
Finalize logo(s) / favicons
Enable social links
Make sure all content is migrated
Make sure no broken links / tags / sanity check HTML / Javascript
Get Kiali / iter8-trend content as well
Make sure ease of navigation for content

**Comment by Alan-Cha** [comment]
- [ ] Replace canary analysis picture
- [ ] Replace grafana picture for iter8-trend
- [X] Star us on Github should take users to the correct location
- [ ] Finalize logo(s) / favicons
- [X] Enable social links
- [ ] Make sure all content is migrated
- [ ] Make sure no broken links / tags / sanity check HTML / Javascript
- [ ] Get Kiali / iter8-trend content as well
- [ ] Make sure ease of navigation for content
- [X] Search bar
- [X] Currently selected page indicator
- [ ] Displaying commands and their output
- [ ] Ensuring that all the documentation is there are makes sense
