### ISSUE TITLE
Create tutorial part to cover addition of new metric via KUI

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/docs#50]
The Part 4 of our tutorial (https://github.com/iter8-tools/docs/blob/master/doc_files/iter8_bookinfo_istio.md#part-4-using-a-custom-metric) needs to be modified according to the new metric definition.

**Comment by fabolive** [comment]
@sriumcp: I am not sure what sprint we should assign this issue to.

**Comment by sriumcp** [comment]
Closing. Will be covered as part of iter8-KUI as appropriate.
