### ISSUE TITLE
Define tutorials for v1.0.0

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#72]
Illustration means both blog and tutorial

Outcomes:
1. Experiment object focusing on canary experiment (2 versions; latency and error related criteria with thresholds)
1.1 success - meets criteria
1.2 fails criteria
1.3 fails criteria and traffic is immediately cut off

2. Experiment object focusing on A/B/N experiment (3 versions; single reward criteria) - -- reward is a user-defined business metric
2.1 with an existing metric for reward
2.2 reward metric is defined by the user

3. Experiment object focusing on constrained A/B/N experiment (3 versions; single reward criteria; multiple other criteria with thresholds) --  version wins in (2) and is not feasible in (3)
** relies on previous user-defined metric

**Comment by kalantar** [comment]
@fabolive I suppose that in 1 above we also want 1.4 - edge service ?

**Comment by kalantar** [comment]
@fabolive I'm thinking we should make the telemetry v2 files the default (with simpler names) and make the v1 the ones with an extension. Does that sound right?  Since we heard that v1 is deprecated.

**Comment by kalantar** [comment]
Discussion 7/28 resulted in three tutorials and some "how to" documentation to explain other features. Closed many of the other tutorial issues and changed name of this epic.

**Comment by sriumcp** [comment]
Tutorials are now out.
