### ISSUE TITLE
Create tutorial parts for canary that fails success criteria

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/docs#76]
Characteristics:

- 2 versions
- latency and error-related success criteria
- canary version does not pass criteria: is is too slow.

Sub-case (a):
  Do not use `cutOffTrafficOnViolation`
Sub-case (b):
  Use `cutOffTrafficOnViolation`

**Comment by kalantar** [comment]
Discussion 7/28 resulted in single canary tutorial: https://github.com/iter8-tools/docs/issues/74. Closing others.
