### ISSUE TITLE
Bookinfo upgrades for v1.0.0

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#93]
@fabolive @kalantar

**Comment by Alan-Cha** [comment]
Change productpage (Python Flask) to emit a metric mimicking revenue
* Prometheus-related change to the deployment yaml
* /metrics endpoint for Prometheus to scrape metrics from the app
* Change the app logic to consume an env variable (probability of buying?) that will model the difference in behavior (in terms for the revenue metric) for each version
