### ISSUE TITLE
Resolve Telemetry Issue

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/docs#99]
Needs more documentation review / discussions.

@jadeyliu939 @huang195 FYI

**Comment by sriumcp** [comment]
Summary of discussion between @huang195 @jadeyliu939 and myself on the issues pertaining iter8_latency since this metric has different units in v1 and v2:

**During Install:** We will have a script to auto-detect v1 vs. v2 and install appropriate iter8 components

**During experiment CR creation in Kiali:** Right now, we handle iter8_latency as a special metric with the Kiali UI being units aware. This solves the problem for Kiali users.

**During experiment CR creation through CLI / in pipelines:** We will make the documentation much easier to follow (by explicitly describing different tutorial / sample templates for v1 and v2. We will also describe what the v1 and v2 difference is very clearly.

**v1.0.0 onwards:** We do need a broader discussion on units in v1.0.0. We will take this up after we nail v0.2.

**Comment by kalantar** [comment]
I suggest we rename our telemetry-v1 tutorial files so that the naming between v1 and v2 is consistent. (ie, add __telemetry-v1_). Then in the doc use a variable to specify which to use. This would help make the tutorial documentation becomes clearer.

The install script should output the version of telemetry discovered and give a line to cut and paste that would set the environment variable used by the tutorial.

**Comment by huang195** [comment]
@sriumcp this is a very good summary of our discussion. I want to add a few more points before I forget. For the time being, we could rely on better documentation and maintain a matrix of yaml files to deal with infrastructure variations. If we assume things will eventually converge, e.g., in v1.7 Istio will drop v1 telemetry support, this temporary solution will work for us without doing too much work. However, if things keep diverging, the current way might not be sustainable, as major releases often break backward compatibility (in our case, minor releases in both Istio and K8s broke things for us. Maybe we were just unlucky). We need to make some guess work here to anticipate how these dependencies will affect us in the future. 

The proposals @jadeyliu939 and I were suggesting were to add additional fields (e.g., Istio version or metric unit) in the metric configmap and/or Experiment CR, along with changes in analytics and controller. Such a change has a big impact throughout Iter8, so would definitely require some design iterations. Once we can focus more on v1.0, we should revisit this topic.

**Comment by sriumcp** [comment]
@huang195 Fair points. We do have an optional `unit` field in the v1.0.0 CR right now. But I think there's scope for more / better design in v1.0.0 for this issue. Yes, we will revisit for sure.

**Comment by sriumcp** [comment]
Current best solution as we've agree on in our discussions.

1. We maintain two configmaps, one for telemetry v1 and another for telemetry v2. The install script will adaptively install the appropriate components. In telemetry v1, we define iter_latency as the current template (which is in seconds) * 1000… in other words, we change the prometheus query template by multiplying it by 1000. Prometheus supports this, so we will basically be getting the results back from prom in millisec.

2. In telemetry v2, we define iter8_latency as in the current template (which is already in millisec).

3. We document all our tutorials — by indicating iter8_latency is measured in millisec. In other words, the step by step tutorials will be identical for both v1 and v2.

4. We can continue to have 2 grafana templates (one for v1 and another for v2) and install that also adaptively.
